### PR TITLE
Make Ruby Gooder Again

### PR DESCRIPTION
**Pull request by adunkman**
What do we think about merging this to `gh-pages` (rubyforgood.org) now? I think we’re pretty well along, and we seem to be at the point where this branch is now better than what’s published.

Thoughts?

### CODE REVIEW

**Comment by juliancheal** [comment]
highest-of-fives-explosion
Deploy all the things 👏

**Comment by csexton** [comment]
Shipit snail

**Comment by csexton** [comment]
I am good getting this deployed. @seanmarcia you wanna give a 👍 ?

**Comment by kalimar** [comment]
I solemnly swear  I heard @seanmarcia say :shipit:

**Comment by adunkman** [comment]
Away we go! 

let’s go for a run

**Pull request merged**
