### PR TITLE
Fix dates

### PR DESCRIPTION
**Pull request by seanmarcia**
Probably shouldn't be the 18th-18th

### CODE REVIEW

**Comment by seanmarcia** [comment]
I blame @kalimar.

**Comment by kalimar** [comment]
Year long event?

**Comment by seanmarcia** [comment]
I assumed that some gal/guy in a blue phone booth was going to show up on the 21st and bring us all back to the 18th...

**Comment by gxespino** [comment]
I expected better from such a talented group of devs/organizers.

**Comment by kalimar** [comment]
snap.

**Pull request merged**
