### PR TITLE
Set ruby version to 2.3.0

### PR DESCRIPTION
**Pull request by kalimar**

### CODE REVIEW

**Comment by csexton** [comment]
8bit-minaswan

**Comment by kalimar** [comment]
summer swan

**Comment by adunkman** [comment]
:thumbsup: 

beemo likes it

**Comment by kalimar** [comment]
@adunkman look good to ya?

**Comment by adunkman** [comment]
Sure, it’s a bit confusing that we have `Gemfile.lock` checked into the repo and also in `.gitignore` — should we just update the checked-in `Gemfile.lock`? Or maybe delete it altogether?

**Comment by kalimar** [comment]
Good point. You solved my mystery. I'll delete it all together. :boom:

**Comment by kalimar** [comment]
Going to PR this on gh-pages instead.

**Pull request closed without merging**
