### PR TITLE
Resolved MINSWAN abbriviation

### LINKED ISSUE #130: Replace MINISWAN with a Spelled Out "Matz is Nice..."
Ruby programmers are generally familiar with "Matz is Nice..." but not so much with the acronym "MINISWAN".  Replace the text "Taking MINISWAN to Heart" with "Matz is Nice So We Are Nice", which says the same thing without making a user click on the phrase to go to Wikipedia.

### PR DESCRIPTION
**Pull request by Jetrie**
Resolves #130

### CODE REVIEW

**Comment by teresafinn** [comment]
@seanmarcia @csexton @kalimar Do you want to unabbreviate "MINASWAN" such that the sentence "Matz is nice so we are nice" replaces the acronym? The logic here from our wonderful designers would be that many people don't know the abbreviation MINASWAN but DO know the unabbreviated version. Thoughts?

**Comment by csexton** [comment]
I thought about this quite a bit, I agree with the goal of making things approachable and easy to understand. I certainly don't want to be unwelcoming. 

I am worried if we spell it out people will not recognize it as an acronym.

Having MINASWAN be a bit of an inside-thing can be helpful, one or the reasons we like to put it on shirts and stickers everywhere. That way we can talk about it, share it at other events, explain it, and hopefully foster the feeling of becoming more a part of the community. Even if it is a silly acronym.

**Comment by craig-riecke** [comment]
I'm cool with that.  The use of MINASWAN has been so pervasive in Ruby For Good that it needs revisiting by fresh eyes every once in awhile.  Thank you for taking that into consideration.

**Comment by csexton** [comment]
I was torn, and happy to re-think things to make sure we want to do things the way we do.

But went back to one of our original _misguided_ directives, which I do feel is a gooder thing:

image

**Pull request closed without merging**
