### PR TITLE
Constantize common data

### PR DESCRIPTION
**Pull request by csexton**
Create constants for a few bits of common data. I am sure there is more that can be refactored out into the `_data` dir, but this gets the files in place so we can easily move things over.

Also included a few minor CSS fixes, mostly for mobile responsive views.

### CODE REVIEW

**Comment by seanmarcia** [comment]
Wow, this is way better. It also closes #112 :)

**Comment by kalimar** [comment]
Assuming it loads, this looks great!

**Comment by csexton** [comment]
Lets merge and we'll find out!

**Comment by kalimar** [comment]
YOLO!

**Comment by csexton** [comment]
image

**Pull request merged**
