### PR TITLE
removed loading spinner from every page

### PR DESCRIPTION
**Pull request by spinecone**
There's not really much on these pages that needs loading, so it seemed unnecessary.

### CODE REVIEW

**Comment by vilmibm** [comment]
:+1:

**Comment by adunkman** [comment]
I’m a 👍, but we might want to see what @csexton has to say, since he just merged #82 this morning.

**Comment by spinecone** [comment]
Yup, I was just testing out his PR and got fed up with the spinner while doing it :)

**Comment by adunkman** [comment]
Fixes #87.

**Comment by vilmibm** [comment]
i'm particularly excited for this pr since i use noscript, which means the page loads with this spinner and then never actually switches to the content until i enable javascript :(

**Comment by csexton** [comment]
Really hard to argue with @nathanielksmith's point on this one 😳 

Lets ship this! @tpinecone you wanna mash the `Merge` button?

**Pull request merged**
