### PR TITLE
adds scholarship information, button, and link to submission form.

### PR DESCRIPTION
**Pull request by asheren**
@cupakromer questions and info look okay to you?

### CODE REVIEW

**Comment by asheren** [comment]
@SeanMarcia always ruining everything. :smile_cat:

**Comment by cupakromer** [comment]
LGTM :+1:

**Comment by seanmarcia** [comment]
I was hoping to wait until the sponsorship information was finalized before putting up scholarship information because ideally it would be nice to have the conference fully sponsored dcamp style so this wouldn't be an issue.
I also updated/changed the form to simplify it and make it less like the rail and rubyconf ones.

**Comment by csexton** [comment]
Sorry, I forgot you wanted to wait on that -- I should have waited to merge. Do you want to me comment it out for now?

I do think not we should not commit to to what a scholarship get you until after we have the sponsorship stuff sorted. But given that we will probably be gathering sponsors up to the last minute it seems like it might be a good idea to start gathering requests.

**Comment by asheren** [comment]
@SeanMarcia I disagree with the scholarship form changes. I definitely think we should at least ask people how attending would help their personal or professional goals.

**Comment by seanmarcia** [comment]
Noted and it is something to consider but I think the very nature of the event answers those kind of questions. I think that if you are coming to an event to work for free, or even to pay a little to do work for socially good causes you can guess what the goals and motivations of the attendees are :smiley:  
That is also why I'm asking where they heard about the event from, because I expect answers like "My friend Evan Light said this would be a great place to meet rubyists, learn some great information, and to make a difference in the world."

**Comment by asheren** [comment]
I get that and my hope is that those are the answers we see. I imagine we'll get more of "someone announced it at DCRug." How can we tell from that if they just want to hang out vs. want to contribute and become a more integral part of the community. I think scholarships should be earned, even if it is just having to put a little bit of additional thought into one additional question. It shows just a tad bit more of commitment. Just my 2 cents.

**Pull request merged**
