### PR TITLE
Corrected typos.

### PR DESCRIPTION
**Pull request by ghost**
I fixed a couple typos in the "Anything else?" section and expanded "August" in the header.

### CODE REVIEW

**Comment by kalimar** [comment]
:+1:

**Comment by ghost** [comment]
Thanks, @kalimar!

Didn't want to send boss to site (to request funding) and have him ask, "When is July 30st and August 2rd?" :blush:

**Comment by seanmarcia** [comment]
:+1:  That's the goodest spelling correction ever! :heart:

**Comment by csexton** [comment]
I 2rd this change!

**Pull request merged**
